// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSConsole
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSConsole.5e9c6d51-cff5-4583-badd-b5033a9d6482";
        public const string Name = "VSConsole";
        public const string Description = @"See selected Console output in a Visual Studio window.";
        public const string Language = "en-US";
        public const string Version = "1.1.1";
        public const string Author = "Matt Lacey";
        public const string Tags = "Console";
    }
}
