// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSConsole
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSCToolWindowPackageString = "94cea740-cfd6-4ef3-a014-eeffa2439433";
        public static Guid guidVSCToolWindowPackage = new Guid(guidVSCToolWindowPackageString);

        public const string guidVSCToolWindowPackageCmdSetString = "fb075fe8-b586-462c-a626-8d9eefdf07fb";
        public static Guid guidVSCToolWindowPackageCmdSet = new Guid(guidVSCToolWindowPackageCmdSetString);

        public const string guidImagesString = "ab64f413-68df-4a67-ac4c-88d1207790e0";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VSCToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}